# -*- coding: utf-8 -*-

DOUBLE_PINYIN_FLYPY_KEY = {
    # 声母
    "INITIALS":{
        "q": "q",
        "w": "w",
        "e": "e",
        "r": "r",
        "t": "t",
        "y": "y",
        "sh": "u",
        "ch": "i",
        "o": "o",
        "p": "p",
        "a": "a",
        "s": "s",
        "d": "d",
        "f": "f",
        "g": "g",
        "h": "h",
        "j": "j",
        "k": "k",
        "l": "l",
        "z": "z",
        "x": "x",
        "c": "c",
        "zh": "v",
        "b": "b",
        "n": "n",
        "m": "m",
    },
    
    # 韵母
    "VOWEL":{
        "iu": "q",
        "ei": "w",
        "uan": "r",
        "ue": "t",
        "un": "y",
        "u": "u",
        "i": "i",
        "o": "o",
        "uo": "o",
        "ie": "p",
        "a": "a",
        "ong": "s",
        "iong": "s",
        "ai": "d",
        "en": "f",
        "eng": "g",
        "ang": "h",
        "an": "j",
        "uai": "k",
        "ing": "k",
        "uang": "l",
        "iang": "l",
        "ou": "z",
        "ua": "x",
        "ia": "x",
        "ao": "c",
        "ui": "v",
        "v": "v",
        "in": "b",
        "iao": "n",
        "ian": "m"
    }
}